[package]
name = "tarpc"
version = "0.6.0"
authors = ["Adam Wright <adam.austin.wright@gmail.com>", "Tim Kuehn <timothy.j.kuehn@gmail.com>"]
license = "MIT"
documentation = "https://docs.rs/tarpc"
homepage = "https://github.com/google/tarpc"
repository = "https://github.com/google/tarpc"
keywords = ["rpc", "protocol", "remote", "procedure", "serialize"]
readme = "README.md"
description = "An RPC framework for Rust with a focus on ease of use."

[dependencies]
bincode = "0.6"
byteorder = "0.5"
bytes = "0.3"
futures = "0.1.7"
lazy_static = "0.2"
log = "0.3"
scoped-pool = "1.0"
serde = "0.8"
serde_derive = "0.8"
tarpc-plugins = { path = "src/plugins" }
take = "0.1"
tokio-service = "0.1"
tokio-proto = "0.1"
tokio-core = "0.1"
net2 = "0.2"

[dev-dependencies]
chrono = "0.2"
env_logger = "0.3"
futures-cpupool = "0.1"
clap = "2.0"

[features]
unstable = ["serde/unstable"]

[workspace]
